#!/usr/bin/env bash
# Читает secrets.env → lamp/gunner47_v2.87in1/wifi_secrets.h (+ matter-bridge/sdkconfig.secrets)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${1:-$ROOT/secrets.env}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Нет $ENV_FILE"
  echo "Сделай: cp secrets.env.example secrets.env  &&  отредактируй  &&  $0"
  exit 1
fi

# shellcheck disable=SC1090
set -a
# shell-style KEY=VALUE; ignore blank/comment lines
# shellcheck source=/dev/null
source <(grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "$ENV_FILE" || true)
set +a

SSID="${WIFI_SSID:-}"
PASS="${WIFI_PASSWORD:-}"

if [[ -z "$SSID" ]]; then
  echo "WIFI_SSID пустой в $ENV_FILE — лампа будет без STA (портал AP)."
fi

escape_c() {
  # escape \ and " for C string literals
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

SSID_C="$(escape_c "$SSID")"
PASS_C="$(escape_c "$PASS")"

cat > "$ROOT/lamp/gunner47_v2.87in1/wifi_secrets.h" <<EOF
#pragma once
/* Generated by scripts/apply_secrets.sh — do not commit */
#define STA_SSID "${SSID_C}"
#define STA_PASS "${PASS_C}"
EOF

cat > "$ROOT/matter-bridge/sdkconfig.secrets" <<EOF
# Generated by scripts/apply_secrets.sh — do not commit
# Matter STA обычно задаёт Алиса; эти поля только для Gyver Bridge Kconfig/логов.
CONFIG_GYVER_WIFI_SSID="${SSID_C}"
CONFIG_GYVER_WIFI_PASSWORD="${PASS_C}"
EOF

echo "OK: lamp/gunner47_v2.87in1/wifi_secrets.h"
echo "OK: matter-bridge/sdkconfig.secrets"
echo "Лампа: открой в Arduino папку lamp/gunner47_v2.87in1/"
echo "Мост: idf.py -D SDKCONFIG_DEFAULTS=\"sdkconfig.defaults;sdkconfig.defaults.esp32c6;sdkconfig.secrets\" ..."
